import { useParams, useNavigate } from 'react-router-dom'
import { useProperty } from '../contexts/PropertyContext'
import { useMetrics, useActiveLease } from '../hooks/useData'
import { computeInvestmentIntelligence } from '../lib/calculations'
import { formatCurrency, formatPct } from '../lib/utils'

export default function IntelligenceDeepDive() {
  const { metric } = useParams<{ metric: string }>()
  const navigate = useNavigate()
  const { activeProperty: prop } = useProperty()
  const { data: metrics } = useMetrics(prop?.id ?? null)
  const activeLease = useActiveLease(prop?.id ?? null)

  const calc = prop ? computeInvestmentIntelligence(prop, metrics, activeLease, 1295.11) : null

  if (!prop || !calc) {
    return <div className="empty-state" style={{ marginTop: 80 }}><p>Loading...</p></div>
  }

  const getMetricDetails = () => {
    switch (metric) {
      case 'gross-equity':
      case 'gross':
        return {
          title: 'Gross Equity',
          value: metrics?.gross_equity != null ? formatCurrency(metrics.gross_equity) : '—',
          color: 'var(--blue)',
          formula: 'Current Market Value - Remaining Loan Balance = Gross Equity',
          math: `${formatCurrency(prop.current_value ?? prop.purchase_price)} - ${formatCurrency(metrics?.remaining_loan_balance ?? prop.loan_amount)} = ${formatCurrency(metrics?.gross_equity ?? 0)}`,
          mathBreakdown: [
            `Current Value (${formatCurrency(prop.current_value ?? prop.purchase_price)}): The latest appraised or market value of the property.`,
            `Remaining Loan Balance (${formatCurrency(metrics?.remaining_loan_balance ?? prop.loan_amount)}): Your current mortgage principal balance. As you pay your mortgage, this number goes down, increasing your equity.`
          ],
          meaning: "Gross Equity is the simplest measure of your wealth in a property. It represents the difference between what the house is worth and what you owe the bank. It does not account for the costs of selling or the cumulative cash you've spent on the property.",
          benchmarks: [
            { label: 'Equity Cushion (Safe)', value: '25%+' },
            { label: 'Wealth Goal', value: '100% (Debt Free)' },
          ]
        }
      case 'net-equity':
      case 'net':
        return {
          title: 'Net Equity (True Cash Out)',
          value: metrics?.net_equity != null ? formatCurrency(metrics.net_equity) : '—',
          color: 'var(--purple)',
          formula: 'Gross Equity - Selling Costs + All-time Net P&L = Net Equity',
          math: `${formatCurrency(metrics?.gross_equity ?? 0)} - ${formatCurrency(metrics?.selling_costs ?? 0)} + ${formatCurrency(metrics?.cumulative_cash_flow ?? 0)} = ${formatCurrency(metrics?.net_equity ?? 0)}`,
          mathBreakdown: [
            `Gross Equity (${formatCurrency(metrics?.gross_equity ?? 0)}): Value minus Debt.`,
            `Estimated Selling Costs (${formatCurrency(metrics?.selling_costs ?? 0)}): A simulated 10% expense for realtor commissions, title fees, and transfer taxes.`,
            `All-time Net P&L (${formatCurrency(metrics?.cumulative_cash_flow ?? 0)}): Every dollar of rent received minus every dollar of expense and closing costs since you purchased the property.`
          ],
          meaning: "Net Equity is your 'True North' for wealth. It represents the actual amount of cash that would hit your bank account if you sold the property today and closed your books. It is 'All-In', meaning it accounts for your original closing costs and all historical profits or losses.",
          benchmarks: [
            { label: 'Break-Even Point', value: '$0' },
            { label: 'Target Cash-on-Cash', value: '2x Invested Capital' },
          ]
        }
      case 'coc':
        return {
          title: 'Cash-on-Cash Return',
          value: calc.cocReturn != null ? formatPct(calc.cocReturn) : '—',
          color: 'var(--green)',
          formula: 'Annualized Cash Flow ÷ Total Cash Deployed = Cash-on-Cash Return',
          math: `${formatCurrency(calc.annualCF ?? 0)} ÷ ${formatCurrency(calc.totalDeployed)} = ${calc.cocReturn ? (calc.cocReturn / 100).toFixed(4) : '—'}`,
          mathBreakdown: [
            `Annualized Cash Flow (${formatCurrency(calc.annualCF ?? 0)}): Generated by taking your exact Cumulative Cash Flow to date, divided by the exact months owned, then multiplied by 12.`,
            `Total Cash Deployed (${formatCurrency(calc.totalDeployed)}): Your initial Down Payment plus all Closing Costs.`
          ],
          meaning: "Cash-on-Cash return tells you exactly what your cash yield is. It answers the question: 'For every dollar I physically put into this property, how many cents am I putting into my pocket each year?' It intentionally excludes invisible wealth builders like principal paydown and appreciation.",
          benchmarks: [
            { label: 'Standard Residential', value: '8.0% – 12.0%' },
            { label: 'A-Class Stable', value: '5.0% – 8.0%' },
            { label: 'High Yield / Value-Add', value: '12.0%+' },
          ]
        }
      case 'yoc':
        return {
          title: 'Yield on Cost (YOC)',
          value: calc.yoc != null ? formatPct(calc.yoc) : '—',
          color: 'var(--teal)',
          formula: 'Current NOI ÷ Total Original Basis = Yield on Cost',
          math: `${formatCurrency(calc.noi)} ÷ ${formatCurrency(prop.purchase_price + prop.closing_costs)} = ${calc.yoc ? (calc.yoc / 100).toFixed(4) : '—'}`,
          mathBreakdown: [
            `Current NOI (${formatCurrency(calc.noi)}): Your annualized Net Operating Income. Calculated as (Monthly Rent × 12) - (Annualized Management + Maintenance + HOA). It excludes your mortgage.`,
            `Original Basis (${formatCurrency(prop.purchase_price + prop.closing_costs)}): The total amount of money required to acquire the property. Purchase Price (${formatCurrency(prop.purchase_price)}) + Closing Costs (${formatCurrency(prop.closing_costs)}).`
          ],
          meaning: "Yield on Cost measures your current yield against the money you originally spent. It ignores current market value and focuses on your personal performance. If you bought a property 10 years ago and rents have doubled, your YOC will be much higher than the market cap rate, showing the power of long-term hold strategies.",
          benchmarks: [
            { label: 'Standard Acquisition', value: '5.0% – 7.0%' },
            { label: 'Successful 5-Yr Hold', value: '8.0% – 11.0%' },
            { label: 'Legacy Asset (10+ Yr)', value: '15.0%+' },
          ]
        }
      case 'roe':
        return {
          title: 'Return on Equity (ROE)',
          value: calc.roe != null ? formatPct(calc.roe) : '—',
          color: 'var(--yellow)',
          formula: 'Annualized Cash Flow ÷ Current Capitalized Net Equity',
          math: `${formatCurrency(calc.annualCF ?? 0)} ÷ ${formatCurrency(calc.capitalizedNetEq ?? 0)} = ${calc.roe ? (calc.roe / 100).toFixed(4) : '—'}`,
          mathBreakdown: [
            `Annualized Cash Flow (${formatCurrency(calc.annualCF ?? 0)}): Your net operating P&L extended to a 12-month period based on historicals.`,
            `Capitalized Net Equity (${formatCurrency(calc.capitalizedNetEq ?? 0)}): The exact dollar amount of cash you would walk away with if you sold the property tomorrow. Calculated as Current Value - Remaining Loan - Selling Costs (${formatPct(8)}).`
          ],
          meaning: "ROE is an extremely advanced metric that helps you answer: 'Should I sell or refinance?' As your equity grows over the years through appreciation and loan paydown, your ROE will drop. If your ROE drops below 4%, it means you have significant equity 'trapped' in the property, signalling it might be time for a cash-out refinance.",
          benchmarks: [
            { label: 'Highly Efficient Equity', value: '10.0% – 15.0%' },
            { label: 'Maturing Investment', value: '5.0% – 8.0%' },
            { label: 'Trapped Dead Equity', value: 'Below 4.0%' },
          ]
        }
      case 'em':
      case 'equity-multiple':
        return {
          title: 'Equity Multiple',
          value: calc.equityMultiple != null ? `${calc.equityMultiple.toFixed(2)}x` : '—',
          color: 'var(--purple)',
          formula: '(Capitalized Net Equity + Total Cash Deployed) ÷ Total Cash Deployed = Equity Multiple',
          math: `(${formatCurrency(calc.capitalizedNetEq ?? 0)} + ${formatCurrency(calc.totalDeployed)}) ÷ ${formatCurrency(calc.totalDeployed)} = ${calc.equityMultiple ? calc.equityMultiple.toFixed(2) : '—'}`,
          mathBreakdown: [
            `Capitalized Net Equity (${formatCurrency(calc.capitalizedNetEq ?? 0)}): Includes all wealth accumulation (Appreciation + Principal Downpay + Cash Flow) minus hypothetical selling costs. This gives you the true 'pull-out' sum of your investment today.`,
            `Total Cash Deployed (${formatCurrency(calc.totalDeployed)}): The initial capital injection required to acquire the asset (Down Payment + Closing Costs).`
          ],
          meaning: "Equity Multiple tells you how much your initial investment has grown across all vectors (cash flow, principal paydown, and appreciation). Unlike IRR, it does not account for the time value of money, but it clearly answers: 'If I put in $1, how much total wealth do I have now?'",
          benchmarks: [
            { label: 'Break-even', value: '1.00x' },
            { label: 'Solid Core Investment (5-7 yrs)', value: '1.50x – 2.00x' },
            { label: 'Home Run / Heavy Value-Add', value: '2.50x+' },
          ]
        }
      case 'rtv':
        return {
          title: 'Rent-to-Value (RTV) Ratio',
          value: calc.rtv != null ? formatPct(calc.rtv) : '—',
          color: 'var(--pink)',
          formula: 'Monthly Rent ÷ Current Property Value = RTV',
          math: `${formatCurrency(calc.monthlyRent)} ÷ ${formatCurrency(prop.current_value ?? prop.purchase_price)} = ${calc.rtv ? (calc.rtv / 100).toFixed(4) : '—'}`,
          mathBreakdown: [
            `Monthly Rent (${formatCurrency(calc.monthlyRent)}): Your current lease rent or simulated monthly income input.`,
            `Current Value (${formatCurrency(prop.current_value ?? prop.purchase_price)}): The latest appraised or market value of the property.`
          ],
          meaning: "The RTV ratio is a quick-and-dirty tool for evaluating rental property performance. A higher RTV means more rent for every dollar of property value. While the '1% Rule' (RTV = 1.0%) is a famous industry benchmark, it is increasingly rare in high-appreciation or modern interest-rate environments.",
          benchmarks: [
            { label: 'The "1% Rule"', value: '1.0%+' },
            { label: 'Strong Rental Market', value: '0.7% – 0.9%' },
            { label: 'High Appreciation Market', value: 'Below 0.5%' },
          ]
        }
      case 'oer':
        return {
          title: 'Operating Expense Ratio (OER)',
          value: calc.oer != null ? formatPct(calc.oer) : '—',
          color: 'var(--red)',
          formula: 'Annual Operating Expenses ÷ Gross Operating Income',
          math: `${formatCurrency(calc.annualOpExp ?? 0)} ÷ ${formatCurrency(calc.annualRent ?? 0)} = ${calc.oer ? (calc.oer / 100).toFixed(4) : '—'}`,
          mathBreakdown: [
            `Annual Operating Expenses (${formatCurrency(calc.annualOpExp ?? 0)}): The annualized sum of Management, Maintenance, HOA, Insurance, and Taxes. It explicitly excludes the mortgage.`,
            `Gross Operating Income (${formatCurrency(calc.annualRent ?? 0)}): Your total potential annual revenue (Monthly Rent × 12).`
          ],
          meaning: "OER measures how lean your property runs. It shows what percentage of your rental income is vaporized by taxes, insurance, maintenance, property management, and HOAs before you even reach the mortgage. Because it excludes mortgage payments, it's a pure indicator of management efficiency.",
          benchmarks: [
            { label: 'Extremely Lean (Self-Managed / No HOA)', value: '25% – 35%' },
            { label: 'Industry Standard "50% Rule"', value: '45% – 50%' },
            { label: 'Very Heavy (High Taxes / Luxury HOA)', value: '55%+' },
          ]
        }
      case 'adjCap':
      case 'adjusted-cap':
        return {
          title: 'Adjusted Cap Rate (w/ Reserves)',
          value: calc.adjustedCapRate != null ? formatPct(calc.adjustedCapRate) : '—',
          color: 'var(--indigo)',
          formula: '(NOI - 5% Capital Reserve) ÷ Property Value = Adjusted Cap Rate',
          math: `(${formatCurrency(calc.noi)} - ${formatCurrency(calc.annualRent * 0.05)}) ÷ ${formatCurrency(prop.current_value ?? prop.purchase_price)} = ${calc.adjustedCapRate ? (calc.adjustedCapRate / 100).toFixed(4) : '—'}`,
          mathBreakdown: [
            `NOI (${formatCurrency(calc.noi)}): Your annualized Net Operating Income (Income - OpEx).`,
            `Capital Reserve (${formatCurrency(calc.annualRent * 0.05)}): A simulated 5% holdback from total rent for future major capital expenditures (Roof, HVAC, etc.).`,
            `Property Value (${formatCurrency(prop.current_value ?? prop.purchase_price)}): The current market or purchase valuation.`
          ],
          meaning: "Standard Cap Rates often produce overly optimistic projections by ignoring the eventual need for major repairs (roof, HVAC, etc.). The Adjusted Cap Rate forces a 5% 'Capital Reserve' into the math, creating a much more accurate reflection of the property's long-term distributable income.",
          benchmarks: [
            { label: 'Conservative Healthy Core', value: '4.5% – 6.0%' },
            { label: 'Marginal Performance', value: '3.0% – 4.5%' },
            { label: 'Value Traps', value: 'Below 2.5%' },
          ]
        }
      case 'pcf':
      case 'proj-cf':
        return {
          title: 'Exp. Annual Cash Flow (Run-Rate)',
          value: calc.projAnnualCF != null ? formatCurrency(calc.projAnnualCF) : '—',
          color: 'var(--green)',
          formula: 'Annual Rent - Annual Operating Expenses - Annual Debt Service = Projected Cash Flow',
          math: `${formatCurrency(calc.annualRent)} - ${formatCurrency(calc.annualOpExp)} - ${formatCurrency(calc.annualDebtService)} = ${calc.projAnnualCF != null ? formatCurrency(calc.projAnnualCF) : '—'}`,
          mathBreakdown: [
            `Annual Rent (${formatCurrency(calc.annualRent)}): Your current monthly rent multiplied by 12. Unlike historical data, this assumes the latest lease rate continues for a full year.`,
            `Annual Operating Expenses (${formatCurrency(calc.annualOpExp)}): Includes TTM management/maintenance plus annualized fixed costs like HOA, Taxes, and Insurance.`,
            `Annual Debt Service (${formatCurrency(calc.annualDebtService)}): The total mortgage payments expected over the next 12 months.`
          ],
          meaning: "This is your forward-looking 'Run Rate'. While other metrics look at what *happened*, this metric looks at what *will happen* over the next 12 months if your current rent and expense levels stay constant. It's the most important number for personal budgeting and planning future acquisitions.",
          benchmarks: [
            { label: 'Positive Cash Flow', value: 'Any amount > $0' },
            { label: 'Healthy Margin', value: '15% of Gross Rent' },
            { label: 'Self-Sustaining Portfolio', value: '$500+ / unit' },
          ]
        }
      case 'refi':
      case 'refi-equity':
        return {
          title: 'Refinance-able Equity (Dry Powder)',
          value: calc.refiEquity != null ? formatCurrency(calc.refiEquity) : '—',
          color: 'var(--blue)',
          formula: '(Current Market Value × 75%) - Remaining Loan Balance = Available Liquidity',
          math: `(${formatCurrency(prop.current_value ?? prop.purchase_price)} × 0.75) - ${formatCurrency(metrics?.remaining_loan_balance ?? prop.loan_amount)} = ${calc.refiEquity != null ? formatCurrency(calc.refiEquity) : '—'}`,
          mathBreakdown: [
            `Max Refinance Loan (${formatCurrency((prop.current_value ?? prop.purchase_price) * 0.75)}): Most conventional lenders will allow a cash-out refinance at a maximum 75% Loan-to-Value (LTV).`,
            `Remaining Loan Balance (${formatCurrency(metrics?.remaining_loan_balance ?? prop.loan_amount)}): Your current principal balance that must be paid off by the new loan.`
          ],
          meaning: "Refinance-able equity is your hidden 'Dry Powder'. It represents the actual liquid cash you could pull out of this property tomorrow to buy another one, while still keeping a safe 25% equity cushion. If this number is high, you are under-leveraged and your wealth compounding is likely slowing down.",
          benchmarks: [
            { label: 'Re-investment Ready', value: '$50,000+' },
            { label: 'Down Payment Coverage', value: 'Enough for 1+ new unit' },
          ]
        }
      case 'loanConstant':
      case 'loan-constant':
        return {
          title: 'Loan Constant',
          value: calc.loanConstant != null ? formatPct(calc.loanConstant) : '—',
          color: 'var(--indigo)',
          formula: 'Annual Debt Service ÷ Total Loan Amount = Loan Constant',
          math: `${formatCurrency(calc.annualDebtService)} ÷ ${formatCurrency(prop.loan_amount)} = ${calc.loanConstant ? (calc.loanConstant / 100).toFixed(4) : '—'}`,
          mathBreakdown: [
            `Annual Debt Service (${formatCurrency(calc.annualDebtService)}): Principal + Interest + Escrow paid over 12 months.`,
            `Total Loan Amount (${formatCurrency(prop.loan_amount)}): The initial amount borrowed from the lender.`
          ],
          meaning: "The Loan Constant measures the true 'percentage cost' of your debt. Think of it as a weighted average of your interest rate and your amortization speed. If your Loan Constant is HIGHER than your Cap Rate, you have 'Negative Leverage'—meaning the money you borrowed is actually costing you more than the property is earning.",
          benchmarks: [
            { label: 'Cheap Capital', value: 'Below 6.0%' },
            { label: 'Balanced Leverage', value: '6.0% – 8.0%' },
            { label: 'Expensive / High Rate', value: 'Above 8.5%' },
          ]
        }
      case 'equityAcc':
      case 'equity-acc':
        return {
          title: 'Equity Accumulation Rate',
          value: calc.equityAccRate != null ? formatPct(calc.equityAccRate) : '—',
          color: 'var(--purple)',
          formula: '(Annual Principal Paydown + Annual Appreciation) ÷ Original Deployed Capital',
          math: `(${formatCurrency(calc.annualPrincipal ?? 0)} + ${formatCurrency(calc.annualAppreciation ?? 0)}) ÷ ${formatCurrency(calc.totalDeployed)} = ${calc.equityAccRate ? (calc.equityAccRate / 100).toFixed(4) : '—'}`,
          mathBreakdown: [
            `Annual Principal (${formatCurrency(calc.annualPrincipal ?? 0)}): The amount of debt reduced by your tenant through their rent as they pay your mortgage.`,
            `Annual Appreciation (${formatCurrency(calc.annualAppreciation ?? 0)}): The estimated market growth of the property value per year.`,
            `Cash Deployed (${formatCurrency(calc.totalDeployed)}): Your initial down payment and closing costs.`
          ],
          meaning: "This is the 'Wealth Engine' of real estate. It ignores cash flow and focuses entirely on how fast your Net Worth is growing inside this specific asset. Even if a property is 'cash flow break-even', it might still be generating 15%+ yearly wealth through this accumulation rate.",
          benchmarks: [
            { label: 'Inflation Hedge', value: '3.0% – 6.0%' },
            { label: 'Wealth Builder', value: '8.0% – 15.0%' },
            { label: 'Aggressive Compounder', value: '20%+' },
          ]
        }
      case 'unleveredYield':
      case 'unlevered-yield':
        return {
          title: 'Unlevered Yield (Pure Asset)',
          value: calc.unleveredYield != null ? formatPct(calc.unleveredYield) : '—',
          color: 'var(--teal)',
          formula: 'Annual NOI ÷ Total Acquisition Cost (Basis) = Unlevered Yield',
          math: `${formatCurrency(calc.noi)} ÷ ${formatCurrency(prop.purchase_price + prop.closing_costs)} = ${calc.unleveredYield ? (calc.unleveredYield / 100).toFixed(4) : '—'}`,
          mathBreakdown: [
            `Net Operating Income (${formatCurrency(calc.noi)}): Your annual profit BEFORE all debt and taxes.`,
            `Total Basis (${formatCurrency(prop.purchase_price + prop.closing_costs)}): The full price you paid (Purchase + Closing Costs).`
          ],
          meaning: "Unlevered yield tells you how the *house* is performing as a machine, regardless of your personal financing choices. It answers the question: 'If I paid 100% cash, what would my ROI be?' This is the best way to compare a rental property to other assets like Treasury Bills or Dividend Stocks.",
          benchmarks: [
            { label: 'Risk-Free Benchmark (T-Bill)', value: 'approx 4.5% – 5.5%' },
            { label: 'Solid Core Rental', value: '6.0% – 8.0%' },
            { label: 'High Yield Cash Play', value: '9.0%+' },
          ]
        }
      case 'yote':
        return {
          title: 'Yield on Trapped Equity (YOTE)',
          value: calc.yote != null ? formatPct(calc.yote) : '—',
          color: 'var(--orange)',
          formula: 'Annual Cash Flow ÷ Current Net Equity (Capitalized)',
          math: `${formatCurrency(calc.annualCF ?? 0)} ÷ ${formatCurrency(calc.capitalizedNetEq ?? 0)} = ${calc.yote ? (calc.yote / 100).toFixed(4) : '—'}`,
          mathBreakdown: [
            `Annualized Cash Flow (${formatCurrency(calc.annualCF ?? 0)}): Your net pocketable profit after all expenses.`,
            `Capitalized Net Equity (${formatCurrency(calc.capitalizedNetEq ?? 0)}): The actual cash you'd walk away with if you sold today (Value - Debt - 10% Selling Costs).`
          ],
          meaning: "Yield on Trapped Equity is the ultimate 'Expert Decision' metric. It measures the ROI you are getting on the equity currently *stuck* in the house. If your YOTE is very low (e.g. 2%), it means your equity is 'lazy'. You could likely sell this house, put that same cash into a simple savings account, and make more money without the work of being a landlord.",
          benchmarks: [
            { label: 'Efficient Equity', value: '8.0%+' },
            { label: 'Lazying Equity (Consider Refi/Sell)', value: '3.0% – 5.0%' },
            { label: 'Dead Equity', value: 'Below 2.5%' },
          ]
        }
      case 'rateStress':
      case 'rate-stress':
        return {
          title: 'Interest Rate Stress Test',
          value: calc.rateStressTest != null ? formatPct(calc.rateStressTest) : '—',
          color: 'var(--red)',
          formula: 'NOI ÷ Remaining Loan Balance = Max Survivable Interest Rate',
          math: `${formatCurrency(calc.noi)} ÷ ${formatCurrency(metrics?.remaining_loan_balance ?? prop.loan_amount)} = ${calc.rateStressTest ? (calc.rateStressTest / 100).toFixed(4) : '—'}`,
          mathBreakdown: [
            `NOI (${formatCurrency(calc.noi)}): Your annual Net Operating Income available to pay a mortgage.`,
            `Current Principal Balance (${formatCurrency(metrics?.remaining_loan_balance ?? prop.loan_amount)}): Your active debt responsibility.`
          ],
          meaning: "This test calculates the 'Failure Point'. It identifies the theoretical maximum interest rate you could pay on your current loan balance before the property stops making any money at all. If the result is 12% and you currently have a 6% loan, you have a massive safety buffer. If it's 6.5%, you are extremely vulnerable to rate hikes on a future refinance.",
          benchmarks: [
            { label: 'Bulletproof Buffer', value: '10.0%+' },
            { label: 'Safe Zone', value: '7.0% – 9.0%' },
            { label: 'High Danger / Thin Margin', value: 'Below 6.0%' },
          ]
        }
      case 'maintAbsorp':
      case 'maint-absorp':
        return {
          title: 'Maintenance Absorption Capacity',
          value: calc.maintAbsorpCap != null ? formatCurrency(calc.maintAbsorpCap) : '$0',
          color: 'var(--orange)',
          formula: 'Annual Cash Flow = Maximum Survivable Maintenance Spike',
          math: `${formatCurrency(calc.annualCF ?? 0)} = ${formatCurrency(calc.maintAbsorpCap ?? 0)}`,
          mathBreakdown: [
            `Annualized Cash Flow (${formatCurrency(calc.annualCF ?? 0)}): Your current projected annual profit.`
          ],
          meaning: "This is a raw 'Stress Test'. It shows the exact dollar amount of additional *unexpected* maintenance expense the property can absorb in a single year before it starts costing you personal money out-of-pocket. It's an indicator of the asset's self-funding resilience during bad years (e.g. if the HVAC and the Roof both fail in July).",
          benchmarks: [
            { label: 'Immune to Routine Repairs', value: '$5,000+' },
            { label: 'Major System Safe', value: '$2,500 – $5,000' },
            { label: 'Fragile (One repair = Loss)', value: 'Below $1,000' },
          ]
        }
      case 'levEffect':
      case 'lev-effect':
        return {
          title: 'Leverage Effect Ratio',
          value: calc.levEffectRatio != null ? calc.levEffectRatio.toFixed(2) : '—',
          color: 'var(--indigo)',
          formula: 'Return on Equity (ROE) ÷ Cap Rate',
          math: `${calc.roe ? (calc.roe / 100).toFixed(4) : '—'} ÷ ${calc.capRate ? (calc.capRate / 100).toFixed(4) : '—'} = ${calc.levEffectRatio ? calc.levEffectRatio.toFixed(2) : '—'}`,
          mathBreakdown: [
            `ROE (${calc.roe ? formatPct(calc.roe) : '—'}): Your return on the equity you've actually built.`,
            `Cap Rate (${calc.capRate ? formatPct(calc.capRate) : '—'}): The raw asset yield assuming no debt.`
          ],
          meaning: "The Leverage Effect Ratio tells you if your debt is actually helping you. If the ratio is GREATER THAN 1.0, your leverage is 'Positive'—meaning you are magnifying your returns through the bank's money. If it's BELOW 1.0, your debt is actually dragging down your ROE, and the property would be more efficient if owned entirely in cash.",
          benchmarks: [
            { label: 'Healthy Positive Leverage', value: '1.20x or higher' },
            { label: 'Neutral Zone', value: '0.90x – 1.10x' },
            { label: 'Destructive Leverage', value: 'Below 0.80x' },
          ]
        }
      case 'amortEff':
      case 'amort-efficiency':
        return {
          title: 'Amortization Efficiency',
          value: calc.amortEff != null ? formatPct(calc.amortEff) : '—',
          color: 'var(--green)',
          formula: 'Monthly Principal Paydown ÷ Full Monthly Mortgage Payment',
          math: `${formatCurrency(calc.annualPrincipal / 12)} ÷ ${formatCurrency(calc.annualDebtService / 12)} = ${calc.amortEff ? (calc.amortEff / 100).toFixed(4) : '—'}`,
          mathBreakdown: [
            `Monthly Principal Paydown (${formatCurrency(calc.annualPrincipal / 12)}): The 'hidden wealth'—actual debt reduction in a single month.`,
            `Total Monthly Payment (${formatCurrency(calc.annualDebtService / 12)}): The full check you write (Principal + Interest + Taxes + Insurance).`
          ],
          meaning: "Amortization Efficiency measures how much of your mortgage check is actually 'profit' vs how much is 'expense' (interest and taxes). In early years of a 30-year mortgage, this number is painfully low (often 10%). As the loan matures, efficiency spikes, meaning your net worth grows faster every month simply by staying in the deal.",
          benchmarks: [
            { label: 'Early-Stage Loan (Years 1-5)', value: '10.0% – 15.0%' },
            { label: 'Mid-Stage Loan (Years 10-15)', value: '25.0% – 35.0%' },
            { label: 'Matured Equity King (Year 25+)', value: 'Above 50.0%' },
          ]
        }
      case 'valueGap':
      case 'value-gap':
        return {
          title: 'Implied Market Value Gap',
          value: calc.marketValGap != null ? formatCurrency(calc.marketValGap) : '—',
          color: 'var(--blue)',
          formula: 'Current Estimated Value - (NOI ÷ 6.5% Benchmark Cap Rate)',
          math: `${formatCurrency(prop.current_value ?? prop.purchase_price)} - (${formatCurrency(calc.noi)} ÷ 0.065) = ${calc.marketValGap != null ? formatCurrency(calc.marketValGap) : '—'}`,
          mathBreakdown: [
            `Our Valuation (${formatCurrency(prop.current_value ?? prop.purchase_price)}): The value we currently have on the books for this property.`,
            `Institutional Valuation (${formatCurrency(calc.noi / 0.065)}): What an institutional buyer would pay based on its Income (NOI) at a standard 6.5% cap rate.`
          ],
          meaning: "The Value Gap tells you if you are overpaying for 'Sentiment' vs 'Income'. If the gap is positive (+$50,000), it means your property is priced as a 'Luxury' or 'Primary-User' home beyond its rental value. If negative (-$50,000), you have found a hidden gem that is worth more in income than its market price suggests.",
          benchmarks: [
            { label: 'Income-Pure Asset', value: 'Gap near $0' },
            { label: 'Over-Valued (High Apprec.)', value: 'Large Positive Gap' },
            { label: 'Under-Valued (Deep Value)', value: 'Significant Negative Gap' },
          ]
        }
      case 'vac-survival':
      case 'vacSurvival':
        return {
          title: 'Vacancy Survival Duration',
          value: calc.vacSurvivalDuration != null ? `${calc.vacSurvivalDuration.toFixed(1)} months` : '—',
          color: 'var(--pink)',
          formula: 'Actual Cumulative Cash Flow ÷ (Monthly OpEx + Monthly Mortgage)',
          math: `${formatCurrency(Math.max(0, metrics?.cumulative_cash_flow ?? 0))} ÷ ${formatCurrency(calc.monthlyOutflow ?? 0)} = ${calc.vacSurvivalDuration ? calc.vacSurvivalDuration.toFixed(1) : '—'} months`,
          mathBreakdown: [
            `Current Cash Reserves (${formatCurrency(Math.max(0, metrics?.cumulative_cash_flow ?? 0))}): Your actual accumulated profit (Cumulative P&L) since acquisition. We assume you haven't touched this cash and it's your primary safety net.`,
            `Monthly Burn Rate (${formatCurrency(calc.monthlyOutflow ?? 0)}): The total monthly cost of holding the property (Mortgage + Taxes + Insurance + HOA + Maintenance) with $0 rental income.`
          ],
          meaning: `This metric calculates exactly how long you can survive a "Total Vacancy" event using only the profits this property has generated so far. It ignores theoretical savings and focuses on the asset's self-funding capability. To reach the gold standard of 12 months of survival, your reserve should be ${formatCurrency(calc.vacTarget12Mo ?? 0)}.`,
          benchmarks: [
            { label: 'Fortress Protection (12 mo)', value: formatCurrency(calc.vacTarget12Mo ?? 0) },
            { label: 'Standard Safety (6 mo)', value: formatCurrency((calc.vacTarget12Mo ?? 0) / 2) },
            { label: 'Minimum Buffer (3 mo)', value: formatCurrency((calc.vacTarget12Mo ?? 0) / 4) },
          ]
        }
      case 'op-efficiency':
      case 'opEffBenchmark':
        return {
          title: 'Op. Efficiency Benchmark',
          value: calc.opEffBenchmark != null ? `${calc.opEffBenchmark.toFixed(2)}x` : '—',
          color: 'var(--orange)',
          formula: 'Your Operating Expense Ratio (OER) ÷ 35% Institutional Target',
          math: `${calc.oer ? (calc.oer / 100).toFixed(4) : '—'} ÷ 0.35 = ${calc.opEffBenchmark ? calc.opEffBenchmark.toFixed(2) : '—'}`,
          mathBreakdown: [
            `Your OER (${calc.oer ? formatPct(calc.oer) : '—'}): What percentage of your rent is currently lost to operational overhead (Taxes, HOA, Mgmt, Maint).`,
            `Target Standard (35%): The institutional gold-standard for a highly efficient single-family rental.`
          ],
          meaning: "This ratio tells you how close you are to 'Institutional Perfection'. A score of 1.0 means you run a perfectly lean 35% OER. If your score is 2.0, you are twice as expensive to operate as the top pros—likely due to high property taxes or inefficient property management fees.",
          benchmarks: [
            { label: 'Institutional Grade', value: '0.80x – 1.10x' },
            { label: 'Standard Professional', value: '1.20x – 1.40x' },
            { label: 'Highly Inefficient', value: 'Above 1.60x' },
          ]
        }
      case 'tax-sensitivity':
      case 'taxSens':
        return {
          title: 'Tax Sensitivity Index',
          value: calc.taxSensIndex != null ? `${calc.taxSensIndex.toFixed(1)}%` : '—',
          color: 'var(--red)',
          formula: '(10% Spike in Fixed Costs) ÷ Annual Cash Flow',
          math: `(${formatCurrency((prop.hoa_amount ?? 0) * 0.10)}) ÷ ${formatCurrency(calc.annualCF ?? 0)} = ${calc.taxSensIndex ? (calc.taxSensIndex / 100).toFixed(4) : '—'}`,
          mathBreakdown: [
            `Simulated Spike (${formatCurrency((prop.hoa_amount ?? 0) * 12 * 0.10)}): We simulate a 10% annual increase in property taxes and insurance (using HOA/Fixed costs as a proxy).`,
            `Your Annual Profit (${formatCurrency(calc.annualCF ?? 0)}): Your net bottom-line cash flow.`
          ],
          meaning: "This index measures how 'brittle' your profit is. It calculates what percentage of your bottom-line profit would be wiped out if property taxes or insurance spiked by just 10%. If this number is 100%, it means a simple tax hike would turn your property into a cash-flow-negative asset.",
          benchmarks: [
            { label: 'Hardened / High Margin', value: 'Below 5.0%' },
            { label: 'Vulnerable', value: '15.0% – 30.0%' },
            { label: 'Critical Risk', value: 'Above 50.0%' },
          ]
        }
      case 'tax-shield':
      case 'shield':
        return {
          title: 'Tax Shield Impact',
          value: calc.taxShieldImpact != null ? formatPct(calc.taxShieldImpact) : '—',
          color: 'var(--indigo)',
          formula: '(Annual Depreciation + Annual Interest + Annual OpEx) ÷ Annual Gross Rent = Tax Shield',
          math: `(${formatCurrency(calc.annualDepreciation)} + ${formatCurrency(calc.annualInterest)} + ${formatCurrency(calc.annualOpExp)}) ÷ ${formatCurrency(calc.annualRent)} = ${calc.taxShieldImpact ? (calc.taxShieldImpact / 100).toFixed(4) : '—'}`,
          mathBreakdown: [
            `Annual Depreciation (${formatCurrency(calc.annualDepreciation)}): Non-cash expense allowed by the IRS (27.5-year schedule).`,
            `Annual Interest (${formatCurrency(calc.annualInterest)}): The portion of your mortgage payment that is fully tax-deductible as a business expense.`,
            `Annual Operating Expenses (${formatCurrency(calc.annualOpExp)}): Includes Property Taxes, Insurance, HOA, Management, and Maintenance.`,
            `Gross Rent (${formatCurrency(calc.annualRent)}): Your total top-line revenue before any deductions.`
          ],
          meaning: "The Tax Shield Impact measures what percentage of your gross rental income is effectively 'invisible' to the IRS. By combining depreciation (a paper loss) with actual deductible expenses like interest and taxes, real estate often allows investors to collect cash flow while reporting a taxable loss. A shield over 100% means the property is actively offsetting your other income.",
          benchmarks: [
            { label: 'Healthy Shield', value: '40% – 70%' },
            { label: 'Tax-Free Income Zone', value: '80% – 100%' },
            { label: 'Loss Harvesting Phase', value: 'Above 100%' },
          ]
        }
      case 'dscr':
        return {
          title: 'Debt Service Coverage Ratio (DSCR)',
          value: calc.dscr != null ? calc.dscr.toFixed(2) : '—',
          color: calc.dscr && calc.dscr >= 1.25 ? 'var(--green)' : 'var(--orange)',
          formula: 'Annual Net Operating Income (NOI) ÷ Annual Debt Service = DSCR',
          math: `${formatCurrency(calc.noi)} ÷ ${formatCurrency(calc.annualDebtService)} = ${calc.dscr ? calc.dscr.toFixed(2) : '—'}`,
          mathBreakdown: [
            `NOI (${formatCurrency(calc.noi)}): Your gross annual rent minus operational expenses (HOA, management, maintenance). Excludes the mortgage itself.`,
            `Annual Debt Service (${formatCurrency(calc.annualDebtService)}): The total amount paid entirely sequentially to your mortgage in a year (Principal + Interest + Escrow).`
          ],
          meaning: "This ratio measures your buffer against default. A DSCR of 1.0 means your income exactly covers your mortgage. Anything above 1.0 is profit margin. Commercial lenders typically require at least a 1.25 DSCR to underwrite a loan, ensuring a 25% safety buffer.",
          benchmarks: [
            { label: 'Bankable (Standard)', value: '1.25x or higher' },
            { label: 'Aggressive / High Leverage', value: '1.10x – 1.24x' },
            { label: 'Underwater / Structurally Negative', value: 'Below 1.00x' },
          ]
        }
      case 'ltv':
        return {
          title: 'Loan-to-Value (LTV)',
          value: calc.ltv != null ? formatPct(calc.ltv) : '—',
          color: 'var(--blue)',
          formula: 'Remaining Loan Balance ÷ Current Property Value = LTV',
          math: `${formatCurrency(metrics?.remaining_loan_balance ?? prop.loan_amount)} ÷ ${formatCurrency(prop.current_value ?? prop.purchase_price)} = ${calc.ltv ? (calc.ltv / 100).toFixed(4) : '—'}`,
          mathBreakdown: [
            `Remaining Loan Balance (${formatCurrency(metrics?.remaining_loan_balance ?? prop.loan_amount)}): Your current mortgage balance (principal only).`,
            `Current Value (${formatCurrency(prop.current_value ?? prop.purchase_price)}): The current market appraisal or purchase price.`
          ],
          meaning: "LTV measures your leverage risk. A low LTV (like 50%) means you have a massive equity cushion; even a significant market crash won't put you underwater. A high LTV (85%+) means even a small price correction could leave you owing the bank more than the house is worth.",
          benchmarks: [
            { label: 'Ultra-Conservative', value: 'Below 50%' },
            { label: 'Standard Leveraged', value: '65% – 75%' },
            { label: 'Highly Leveraged', value: 'Above 85%' },
          ]
        }
      case 'debtYield':
      case 'debt-yield':
        return {
          title: 'Debt Yield',
          value: calc.debtYield ?? 0,
          color: 'var(--teal)',
          formula: 'Annual NOI ÷ Loan Amount = Debt Yield',
          math: `${formatCurrency(calc.noi)} ÷ ${formatCurrency(prop.loan_amount)} = ${calc.debtYield ? (calc.debtYield / 100).toFixed(4) : '—'}`,
          mathBreakdown: [
            `Annual NOI (${formatCurrency(calc.noi)}): Your annualized Net Operating Income.`,
            `Loan Amount (${formatCurrency(prop.loan_amount)}): The original total borrowed amount from the bank.`
          ],
          meaning: "Debt Yield is the primary metric institutional lenders use because it ignores interest rates and amortization. It tells the bank how many years of property income it would take to recover their loan amount if they had to take the property back today. Lenders typically look for 8-10% to feel safe.",
          benchmarks: [
            { label: 'Institutional Grade', value: '10.0%+' },
            { label: 'Standard / Bankable', value: '8.0% – 10.0%' },
            { label: 'Riskier Entry', value: 'Below 7.0%' },
          ]
        }
      case 'ber':
      case 'breakeven-occupancy':
        return {
          title: 'Break-Even Occupancy Ratio',
          value: calc.breakEvenOccupancy != null ? formatPct(calc.breakEvenOccupancy) : '—',
          color: 'var(--teal)',
          formula: '(Annual Operating Expenses + Annual Debt Service) ÷ Gross Potential Rent',
          math: `(${formatCurrency(calc.annualOpExp ?? 0)} + ${formatCurrency(calc.annualDebtService ?? 0)}) ÷ ${formatCurrency(calc.annualRent ?? 0)} = ${calc.breakEvenOccupancy ? (calc.breakEvenOccupancy / 100).toFixed(4) : '—'}`,
          mathBreakdown: [
            `Total Carrying Cost (${formatCurrency((calc.annualOpExp ?? 0) + (calc.annualDebtService ?? 0))}): The annualized sum of all Operating Expenses (${formatCurrency(calc.annualOpExp ?? 0)}) plus all Mortgage/Debt payments (${formatCurrency(calc.annualDebtService ?? 0)}).`,
            `Gross Potential Rent (${formatCurrency(calc.annualRent ?? 0)}): The total possible annual revenue if the property stayed 100% occupied.`
          ],
          meaning: "This tells you exactly how bulletproof your investment is against vacancies. If your Break-Even Occupancy is 70%, that means 3 months out of the year the house can sit empty, and you still won't have to pull money out of your own pocket to pay the bank.",
          benchmarks: [
            { label: 'Bulletproof (Extremely Safe)', value: 'Below 65%' },
            { label: 'Standard Safe Target', value: '70% – 75%' },
            { label: 'Risky / Thin Margins', value: 'Above 85%' },
          ]
        }
      case 'sensitivity':
        return {
          title: 'Interest Sensitivity',
          value: calc.interestSensitivity != null ? `${calc.interestSensitivity.toFixed(1)}%` : '—',
          color: 'var(--red)',
          formula: '(1% Loan Amount Change) ÷ Current Annual Cash Flow',
          math: `(${formatCurrency(prop.loan_amount * 0.01)}) ÷ ${formatCurrency(calc.annualCF ?? 0)} = ${calc.interestSensitivity ? (calc.interestSensitivity / 100).toFixed(4) : '—'}`,
          mathBreakdown: [
            `Simulated Interest Hike (${formatCurrency(prop.loan_amount * 0.01)}): The estimated annual cost of a 1% increase in your interest rate, based on your original loan of ${formatCurrency(prop.loan_amount)}.`,
            `Current Annual Cash Flow (${formatCurrency(calc.annualCF ?? 0)}): Your current annualized operational profit.`
          ],
          meaning: "Interest sensitivity shows you how much your annual cash flow is at risk if interest rates were 1% higher. This is critical for thinking about variable rate loans or future refinances. If sensitivity is 50%, a 1% rate hike would swallow half of your profit.",
          benchmarks: [
            { label: 'Stable / Hedged', value: 'Below 20%' },
            { label: 'Moderate Risk', value: '25% – 50%' },
            { label: 'Extremely Sensitive', value: 'Above 75%' },
          ]
        }
      case 'capture':
        return {
          title: 'Equity Capture',
          value: calc.equityCapture != null ? formatPct(calc.equityCapture) : '—',
          color: 'var(--purple)',
          formula: '(Current Profit over Basis) ÷ Total Basis = Equity Capture',
          math: `(${formatCurrency((prop.current_value ?? prop.purchase_price) - (prop.purchase_price + prop.closing_costs))}) ÷ ${formatCurrency(prop.purchase_price + prop.closing_costs)} = ${calc.equityCapture ? (calc.equityCapture / 100).toFixed(4) : '—'}`,
          mathBreakdown: [
            `Unrealized Profit (${formatCurrency((prop.current_value ?? prop.purchase_price) - (prop.purchase_price + prop.closing_costs))}): Current Market Value (${formatCurrency(prop.current_value ?? prop.purchase_price)}) minus your total original cash basis (${formatCurrency(prop.purchase_price + prop.closing_costs)}).`,
            `Total Basis (${formatCurrency(prop.purchase_price + prop.closing_costs)}): The total purchase price plus original closing costs.`
          ],
          meaning: "Equity Capture is your 'unrealized ROI'. It shows how much you have increased the original capital you deployed, strictly through value growth and appreciation. It captures the gain you would lock in at the moment of sale.",
          benchmarks: [
            { label: 'Strong Buy (Locked Gain)', value: '10.0%+' },
            { label: 'Mature Investment', value: '30.0% – 50.0%' },
            { label: 'Grand Slam', value: '100%+' },
          ]
        }
      case 'total-return':
      case 'tar':
        return {
          title: 'Total Annualized Return',
          value: calc.wealthCompVelocity != null ? formatPct(calc.wealthCompVelocity) : '—',
          color: 'var(--purple)',
          formula: '(Annual Cash Flow + Annual Principal Paydown + Annual Appreciation) ÷ Total Cash Deployed',
          math: `(${formatCurrency(calc.annualCF ?? 0)} + ${formatCurrency(calc.annualPrincipal ?? 0)} + ${formatCurrency(calc.annualAppreciation ?? 0)}) ÷ ${formatCurrency(calc.totalDeployed)} = ${calc.wealthCompVelocity ? (calc.wealthCompVelocity / 100).toFixed(4) : '—'}`,
          mathBreakdown: [
            `Annualized Cash Flow (${formatCurrency(calc.annualCF ?? 0)}): Pure operational profit taking into account all expenses and debt service.`,
            `Annual Principal Paydown (${formatCurrency(calc.annualPrincipal ?? 0)}): The amount of the mortgage loan that the tenant paid down for you this year.`,
            `Annual Appreciation (${formatCurrency(calc.annualAppreciation ?? 0)}): The estimated growth in property value annualized over the hold period.`,
            `Total Cash Deployed (${formatCurrency(calc.totalDeployed)}): The denominator. Down payment + closing costs.`
          ],
          meaning: "Total Annualized Return acts like a simplified IRR (Internal Rate of Return). It takes all three major wealth generation distinct vectors of real estate—cash flow, mortgage paydown, and equity appreciation—and aggregates them into one powerful percentage. This lets you compare your entire real estate engine directly against the S&P 500 or bond yields.",
          benchmarks: [
            { label: 'S&P 500 Average', value: '7.0% – 10.0%' },
            { label: 'Healthy Real Estate Total Return', value: '12.0% – 18.0%' },
            { label: 'Exceptional Performers', value: '20.0%+' },
          ]
        }
      default:
        return null
    }
  }

  const details = getMetricDetails()
  if (!details) return <div className="empty-state" style={{ marginTop: 80 }}><p>Metric not found.</p></div>

  return (
    <main className="page-content" style={{ maxWidth: 800 }}>
      {/* Back button */}
      <button onClick={() => navigate(-1)} className="btn btn-ghost" style={{ paddingLeft: 0, marginBottom: 24, alignSelf: 'flex-start' }}>
        ← Back to Overview
      </button>

      <div className="card" style={{ padding: '40px', borderTop: `6px solid ${details.color}` }}>
        <h1 style={{ fontSize: '2.5rem', marginBottom: 8 }}>{details.title}</h1>
        <div style={{ fontFamily: 'var(--font-mono)', fontWeight: 800, fontSize: '3rem', color: details.color, marginBottom: 32 }}>
          {details.value}
        </div>

        <div style={{ marginBottom: 40 }}>
          <h3 className="section-title" style={{ fontSize: '1rem', color: 'var(--text-muted)', marginBottom: 12 }}>What it tells you</h3>
          <p style={{ fontSize: '1.05rem', lineHeight: 1.6 }}>{details.meaning}</p>
        </div>

        <div style={{ padding: '24px', background: 'var(--surface-1)', borderRadius: 'var(--radius-lg)', border: '1px solid var(--border)', marginBottom: 40 }}>
          <h3 className="section-title" style={{ fontSize: '1rem', color: 'var(--text-muted)', marginBottom: 16 }}>The Calculation</h3>
          <div style={{ fontSize: '0.9rem', color: 'var(--text-muted)', marginBottom: 8 }}>{details.formula}</div>
          <div style={{ fontFamily: 'var(--font-mono)', fontSize: '1.25rem', padding: '16px', background: 'var(--surface-3)', borderRadius: 'var(--radius-md)', fontWeight: 600, marginBottom: details.mathBreakdown ? 20 : 0 }}>
            {details.math}
          </div>
          {details.mathBreakdown && (
            <div style={{ display: 'flex', flexDirection: 'column', gap: 12, marginTop: 16 }}>
              {details.mathBreakdown.map((txt, idx) => {
                const [boldPart, rest] = txt.split(/:(.+)/)
                return (
                  <div key={idx} style={{ fontSize: '0.875rem', color: 'var(--text-subtle)', display: 'flex', gap: 8, alignItems: 'flex-start' }}>
                    <span style={{ color: details.color, fontSize: '1.2rem', lineHeight: '1rem' }}>•</span>
                    <div>
                      {rest ? <><strong style={{ color: 'var(--text-muted)' }}>{boldPart}:</strong>{rest}</> : txt}
                    </div>
                  </div>
                )
              })}
            </div>
          )}
        </div>

        <div>
          <h3 className="section-title" style={{ fontSize: '1rem', color: 'var(--text-muted)', marginBottom: 16 }}>Industry Benchmarks</h3>
          <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
            {details.benchmarks.map((b, i) => (
              <div key={i} style={{ display: 'flex', justifyContent: 'space-between', padding: '16px 20px', background: 'var(--surface-3)', borderRadius: 'var(--radius-md)' }}>
                <span style={{ fontWeight: 500 }}>{b.label}</span>
                <span style={{ fontFamily: 'var(--font-mono)', color: 'var(--text-muted)' }}>{b.value}</span>
              </div>
            ))}
          </div>
        </div>
      </div>
    </main>
  )
}
