import { useParams, useNavigate } from 'react-router-dom'
import { useProperty } from '../contexts/PropertyContext'
import { useMetrics, useActiveLease } from '../hooks/useData'
import { computeInvestmentIntelligence } from '../lib/calculations'
import { formatCurrency, formatPct } from '../lib/utils'

export default function IntelligenceDeepDive() {
  const { metric } = useParams<{ metric: string }>()
  const navigate = useNavigate()
  const { activeProperty: prop } = useProperty()
  const { data: metrics } = useMetrics(prop?.id ?? null)
  const activeLease = useActiveLease(prop?.id ?? null)

  const calc = prop ? computeInvestmentIntelligence(prop, metrics, activeLease, 1295.11) : null

  if (!prop || !calc) {
    return <div className="empty-state" style={{ marginTop: 80 }}><p>Loading...</p></div>
  }

  const getMetricDetails = () => {
    switch (metric) {
      case 'coc':
        return {
          title: 'Cash-on-Cash Return',
          value: calc.cocReturn != null ? `${calc.cocReturn.toFixed(2)}%` : '—',
          color: 'var(--green)',
          formula: 'Annualized Cash Flow ÷ Total Cash Deployed = Cash-on-Cash Return',
          math: `${formatCurrency(calc.annualCF ?? 0)} ÷ ${formatCurrency(calc.totalDeployed)} = ${calc.cocReturn ? (calc.cocReturn/100).toFixed(4) : '—'}`,
          mathBreakdown: [
            `Annualized Cash Flow (${formatCurrency(calc.annualCF ?? 0)}): Generated by taking your exact Cumulative Cash Flow (${formatCurrency(metrics?.cumulative_cash_flow ?? 0)}) to date, divided by the exact months owned (${calc.monthsOwned}), then multiplied by 12.`,
            `Total Cash Deployed (${formatCurrency(calc.totalDeployed)}): Your initial Down Payment (${formatCurrency(calc.downPayment)}) plus all Closing Costs (${formatCurrency(prop.closing_costs)}).`
          ],
          meaning: "Cash-on-Cash return tells you exactly what your cash yield is. It answers the question: 'For every dollar I physically put into this property, how many cents am I putting into my pocket each year?' It intentionally excludes invisible wealth builders like principal paydown and appreciation.",
          benchmarks: [
            { label: 'Standard Residential', value: '8.0% – 12.0%' },
            { label: 'A-Class Stable', value: '5.0% – 8.0%' },
            { label: 'High Yield / Value-Add', value: '12.0%+' },
          ]
        }
      case 'cap-rate':
        return {
          title: 'Capitalization Rate (Cap Rate)',
          value: calc.capRate != null ? formatPct(calc.capRate) : '—',
          color: 'var(--blue)',
          formula: 'Annual Net Operating Income (NOI) ÷ Current Property Value = Cap Rate',
          math: `${formatCurrency(calc.noi)} ÷ ${formatCurrency(prop.current_value ?? prop.purchase_price)} = ${calc.capRate ? (calc.capRate/100).toFixed(4) : '—'}`,
          mathBreakdown: [
            `NOI (${formatCurrency(calc.noi)}): Your gross annual rent (${formatCurrency(calc.annualRent)}) minus your annualized operational expenses (${formatCurrency(calc.annualOpExp)}).`,
            `Operating Expenses (${formatCurrency(calc.annualOpExp)}): Includes annualized management fees + expected maintenance + annual HOA dues (${formatCurrency(prop.hoa_amount ?? 0)}). It explicitly EXCLUDES your mortgage payments.`,
            `Property Value (${formatCurrency(prop.current_value ?? prop.purchase_price)}): Utilizing the current estimated value, or falling back to the original purchase price if no estimate is provided.`
          ],
          meaning: "The Cap Rate indicates the unlevered yield of a property. By excluding your mortgage, it acts as a universal ruler to compare one property's operational profitability directly against another's, regardless of how they are financed.",
          benchmarks: [
            { label: 'Class A (Low Risk, Stable)', value: '4.0% – 5.5%' },
            { label: 'Class B (Average Risk)', value: '5.5% – 7.5%' },
            { label: 'Class C (Higher Risk)', value: '7.5% – 10.0%+' },
          ]
        }
      case 'dscr':
        return {
          title: 'Debt Service Coverage Ratio (DSCR)',
          value: calc.dscr != null ? calc.dscr.toFixed(2) : '—',
          color: calc.dscr && calc.dscr >= 1.25 ? 'var(--green)' : 'var(--orange)',
          formula: 'Annual Net Operating Income (NOI) ÷ Annual Debt Service = DSCR',
          math: `${formatCurrency(calc.noi)} ÷ ${formatCurrency(calc.annualDebtService)} = ${calc.dscr ? calc.dscr.toFixed(2) : '—'}`,
          mathBreakdown: [
            `NOI (${formatCurrency(calc.noi)}): Your gross annual rent minus operational expenses (HOA, management, maintenance). Excludes the mortgage itself.`,
            `Annual Debt Service (${formatCurrency(calc.annualDebtService)}): The total amount paid entirely sequentially to your mortgage in a year (Principal + Interest + Escrow).`
          ],
          meaning: "This ratio measures your buffer against default. A DSCR of 1.0 means your income exactly covers your mortgage. Anything above 1.0 is profit margin. Commercial lenders typically require at least a 1.25 DSCR to underwrite a loan, ensuring a 25% safety buffer.",
          benchmarks: [
            { label: 'Bankable (Standard)', value: '1.25x or higher' },
            { label: 'Aggressive / High Leverage', value: '1.10x – 1.24x' },
            { label: 'Underwater / Structurally Negative', value: 'Below 1.00x' },
          ]
        }
      case 'equity-multiple':
        return {
          title: 'Equity Multiple',
          value: calc.equityMultiple != null ? `${calc.equityMultiple.toFixed(2)}x` : '—',
          color: 'var(--purple)',
          formula: '(Capitalized Net Equity + Total Cash Deployed) ÷ Total Cash Deployed = Equity Multiple',
          math: `(${formatCurrency(calc.capitalizedNetEq ?? 0)} + ${formatCurrency(calc.totalDeployed)}) ÷ ${formatCurrency(calc.totalDeployed)} = ${calc.equityMultiple ? calc.equityMultiple.toFixed(2) : '—'}`,
          mathBreakdown: [
            `Capitalized Net Equity (${formatCurrency(calc.capitalizedNetEq ?? 0)}): Includes all wealth accumulation (Appreciation + Principal Downpay + Cash Flow) minus hypothetical selling costs. This gives you the true 'pull-out' sum of your investment today.`,
            `Total Cash Deployed (${formatCurrency(calc.totalDeployed)}): The initial capital injection required to acquire the asset (Down Payment + Closing Costs).`
          ],
          meaning: "Equity Multiple tells you how much your initial investment has grown across all vectors (cash flow, principal paydown, and appreciation). Unlike IRR, it does not account for the time value of money, but it clearly answers: 'If I put in $1, how much total wealth do I have now?'",
          benchmarks: [
            { label: 'Break-even', value: '1.00x' },
            { label: 'Solid Core Investment (5-7 yrs)', value: '1.50x – 2.00x' },
            { label: 'Home Run / Heavy Value-Add', value: '2.50x+' },
          ]
        }
      case 'cash-deployed':
        return {
          title: 'Total Cash Deployed',
          value: formatCurrency(calc.totalDeployed),
          color: 'var(--yellow)',
          formula: 'Down Payment + Total Closing Costs = Total Cash Deployed',
          math: `${formatCurrency(calc.downPayment)} + ${formatCurrency(prop.closing_costs)} = ${formatCurrency(calc.totalDeployed)}`,
          meaning: "This is your true 'skin in the game'. It's the total upfront, un-leveraged capital you wired to the title company on closing day. This number forms the denominator for nearly all return-on-investment calculations.",
          benchmarks: [
            { label: 'FHA / Primary Hustle', value: '3.5% – 5% down' },
            { label: 'Standard Investment Loan', value: '20% – 25% down' },
            { label: 'DSCR / Commercial Loan', value: '20% – 30% down' },
          ]
        }
      case 'interest-ratio':
        return {
          title: 'Interest to Principal Ratio',
          value: calc.interestRatio != null ? `${calc.interestRatio.toFixed(2)} : 1` : '—',
          color: 'var(--orange)',
          formula: 'Total Interest Paid to Date ÷ Total Principal Paid to Date',
          math: `${formatCurrency(calc.totalInterestPaid)} ÷ ${formatCurrency(calc.totalPrincipalPaid)} = ${calc.interestRatio ? calc.interestRatio.toFixed(2) : '—'}`,
          meaning: "A 30-year fixed mortgage is heavily front-loaded with interest. In the early years, you might pay $4 in interest for every $1 of principal you pay down. Over time, as the principal decreases, this ratio flips in your favor.",
          benchmarks: [
            { label: 'Years 1-5 (7% Rate)', value: 'approx 4.0 – 6.0 : 1' },
            { label: 'Years 15-20 (Midway)', value: 'approx 1.5 – 1.0 : 1' },
            { label: 'Years 25-30 (Payoff)', value: 'Sub 0.5 : 1' },
          ]
        }
      default:
        return null
    }
  }

  const details = getMetricDetails()
  if (!details) return <div className="empty-state" style={{ marginTop: 80 }}><p>Metric not found.</p></div>

  return (
    <main className="page-content" style={{ maxWidth: 800 }}>
      {/* Back button */}
      <button onClick={() => navigate(-1)} className="btn btn-ghost" style={{ paddingLeft: 0, marginBottom: 24, alignSelf: 'flex-start' }}>
        ← Back to Overview
      </button>

      <div className="card" style={{ padding: '40px', borderTop: `6px solid ${details.color}` }}>
        <h1 style={{ fontSize: '2.5rem', marginBottom: 8 }}>{details.title}</h1>
        <div style={{ fontFamily: 'var(--font-mono)', fontWeight: 800, fontSize: '3rem', color: details.color, marginBottom: 32 }}>
          {details.value}
        </div>

        <div style={{ marginBottom: 40 }}>
          <h3 className="section-title" style={{ fontSize: '1rem', color: 'var(--text-muted)', marginBottom: 12 }}>What it tells you</h3>
          <p style={{ fontSize: '1.05rem', lineHeight: 1.6 }}>{details.meaning}</p>
        </div>

        <div style={{ padding: '24px', background: 'var(--surface-1)', borderRadius: 'var(--radius-lg)', border: '1px solid var(--border)', marginBottom: 40 }}>
          <h3 className="section-title" style={{ fontSize: '1rem', color: 'var(--text-muted)', marginBottom: 16 }}>The Calculation</h3>
          <div style={{ fontSize: '0.9rem', color: 'var(--text-muted)', marginBottom: 8 }}>{details.formula}</div>
          <div style={{ fontFamily: 'var(--font-mono)', fontSize: '1.25rem', padding: '16px', background: 'var(--surface-3)', borderRadius: 'var(--radius-md)', fontWeight: 600, marginBottom: details.mathBreakdown ? 20 : 0 }}>
            {details.math}
          </div>
          {details.mathBreakdown && (
            <div style={{ display: 'flex', flexDirection: 'column', gap: 12, marginTop: 16 }}>
              {details.mathBreakdown.map((txt, idx) => {
                const [boldPart, rest] = txt.split(/:(.+)/)
                return (
                  <div key={idx} style={{ fontSize: '0.875rem', color: 'var(--text-subtle)', display: 'flex', gap: 8, alignItems: 'flex-start' }}>
                    <span style={{ color: details.color, fontSize: '1.2rem', lineHeight: '1rem' }}>•</span>
                    <div>
                      {rest ? <><strong style={{ color: 'var(--text-muted)' }}>{boldPart}:</strong>{rest}</> : txt}
                    </div>
                  </div>
                )
              })}
            </div>
          )}
        </div>

        <div>
          <h3 className="section-title" style={{ fontSize: '1rem', color: 'var(--text-muted)', marginBottom: 16 }}>Industry Benchmarks</h3>
          <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
            {details.benchmarks.map((b, i) => (
              <div key={i} style={{ display: 'flex', justifyContent: 'space-between', padding: '16px 20px', background: 'var(--surface-3)', borderRadius: 'var(--radius-md)' }}>
                <span style={{ fontWeight: 500 }}>{b.label}</span>
                <span style={{ fontFamily: 'var(--font-mono)', color: 'var(--text-muted)' }}>{b.value}</span>
              </div>
            ))}
          </div>
        </div>
      </div>
    </main>
  )
}
