import { useParams, useNavigate } from 'react-router-dom'
import { useProperty } from '../contexts/PropertyContext'
import { useMetrics, useActiveLease } from '../hooks/useData'
import { computeInvestmentIntelligence } from '../lib/calculations'
import { formatCurrency, formatPct } from '../lib/utils'

export default function IntelligenceDeepDive() {
  const { metric } = useParams<{ metric: string }>()
  const navigate = useNavigate()
  const { activeProperty: prop } = useProperty()
  const { data: metrics } = useMetrics(prop?.id ?? null)
  const activeLease = useActiveLease(prop?.id ?? null)

  const calc = prop ? computeInvestmentIntelligence(prop, metrics, activeLease, 1295.11) : null

  if (!prop || !calc) {
    return <div className="empty-state" style={{ marginTop: 80 }}><p>Loading...</p></div>
  }

  const getMetricDetails = () => {
    switch (metric) {
      case 'coc':
        return {
          title: 'Cash-on-Cash Return',
          value: calc.cocReturn != null ? `${calc.cocReturn.toFixed(2)}%` : '—',
          color: 'var(--green)',
          formula: 'Annualized Cash Flow ÷ Total Cash Deployed = Cash-on-Cash Return',
          math: `${formatCurrency(calc.annualCF ?? 0)} ÷ ${formatCurrency(calc.totalDeployed)} = ${calc.cocReturn ? (calc.cocReturn/100).toFixed(4) : '—'}`,
          mathBreakdown: [
            `Annualized Cash Flow (${formatCurrency(calc.annualCF ?? 0)}): Generated by taking your exact Cumulative Cash Flow (${formatCurrency(metrics?.cumulative_cash_flow ?? 0)}) to date, divided by the exact months owned (${calc.monthsOwned}), then multiplied by 12.`,
            `Total Cash Deployed (${formatCurrency(calc.totalDeployed)}): Your initial Down Payment (${formatCurrency(calc.downPayment)}) plus all Closing Costs (${formatCurrency(prop.closing_costs)}).`
          ],
          meaning: "Cash-on-Cash return tells you exactly what your cash yield is. It answers the question: 'For every dollar I physically put into this property, how many cents am I putting into my pocket each year?' It intentionally excludes invisible wealth builders like principal paydown and appreciation.",
          benchmarks: [
            { label: 'Standard Residential', value: '8.0% – 12.0%' },
            { label: 'A-Class Stable', value: '5.0% – 8.0%' },
            { label: 'High Yield / Value-Add', value: '12.0%+' },
          ]
        }
      case 'cap-rate':
        return {
          title: 'Capitalization Rate (Cap Rate)',
          value: calc.capRate != null ? formatPct(calc.capRate) : '—',
          color: 'var(--blue)',
          formula: 'Annual Net Operating Income (NOI) ÷ Current Property Value = Cap Rate',
          math: `${formatCurrency(calc.noi)} ÷ ${formatCurrency(prop.current_value ?? prop.purchase_price)} = ${calc.capRate ? (calc.capRate/100).toFixed(4) : '—'}`,
          mathBreakdown: [
            `NOI (${formatCurrency(calc.noi)}): Your gross annual rent (${formatCurrency(calc.annualRent)}) minus your annualized operational expenses (${formatCurrency(calc.annualOpExp)}).`,
            `Operating Expenses (${formatCurrency(calc.annualOpExp)}): Includes annualized management fees + expected maintenance + annual HOA dues (${formatCurrency(prop.hoa_amount ?? 0)}). It explicitly EXCLUDES your mortgage payments.`,
            `Property Value (${formatCurrency(prop.current_value ?? prop.purchase_price)}): Utilizing the current estimated value, or falling back to the original purchase price if no estimate is provided.`
          ],
          meaning: "The Cap Rate indicates the unlevered yield of a property. By excluding your mortgage, it acts as a universal ruler to compare one property's operational profitability directly against another's, regardless of how they are financed.",
          benchmarks: [
            { label: 'Class A (Low Risk, Stable)', value: '4.0% – 5.5%' },
            { label: 'Class B (Average Risk)', value: '5.5% – 7.5%' },
            { label: 'Class C (Higher Risk)', value: '7.5% – 10.0%+' },
          ]
        }
      case 'dscr':
        return {
          title: 'Debt Service Coverage Ratio (DSCR)',
          value: calc.dscr != null ? calc.dscr.toFixed(2) : '—',
          color: calc.dscr && calc.dscr >= 1.25 ? 'var(--green)' : 'var(--orange)',
          formula: 'Annual Net Operating Income (NOI) ÷ Annual Debt Service = DSCR',
          math: `${formatCurrency(calc.noi)} ÷ ${formatCurrency(calc.annualDebtService)} = ${calc.dscr ? calc.dscr.toFixed(2) : '—'}`,
          mathBreakdown: [
            `NOI (${formatCurrency(calc.noi)}): Your gross annual rent minus operational expenses (HOA, management, maintenance). Excludes the mortgage itself.`,
            `Annual Debt Service (${formatCurrency(calc.annualDebtService)}): The total amount paid entirely sequentially to your mortgage in a year (Principal + Interest + Escrow).`
          ],
          meaning: "This ratio measures your buffer against default. A DSCR of 1.0 means your income exactly covers your mortgage. Anything above 1.0 is profit margin. Commercial lenders typically require at least a 1.25 DSCR to underwrite a loan, ensuring a 25% safety buffer.",
          benchmarks: [
            { label: 'Bankable (Standard)', value: '1.25x or higher' },
            { label: 'Aggressive / High Leverage', value: '1.10x – 1.24x' },
            { label: 'Underwater / Structurally Negative', value: 'Below 1.00x' },
          ]
        }
      case 'equity-multiple':
        return {
          title: 'Equity Multiple',
          value: calc.equityMultiple != null ? `${calc.equityMultiple.toFixed(2)}x` : '—',
          color: 'var(--purple)',
          formula: '(Capitalized Net Equity + Total Cash Deployed) ÷ Total Cash Deployed = Equity Multiple',
          math: `(${formatCurrency(calc.capitalizedNetEq ?? 0)} + ${formatCurrency(calc.totalDeployed)}) ÷ ${formatCurrency(calc.totalDeployed)} = ${calc.equityMultiple ? calc.equityMultiple.toFixed(2) : '—'}`,
          mathBreakdown: [
            `Capitalized Net Equity (${formatCurrency(calc.capitalizedNetEq ?? 0)}): Includes all wealth accumulation (Appreciation + Principal Downpay + Cash Flow) minus hypothetical selling costs. This gives you the true 'pull-out' sum of your investment today.`,
            `Total Cash Deployed (${formatCurrency(calc.totalDeployed)}): The initial capital injection required to acquire the asset (Down Payment + Closing Costs).`
          ],
          meaning: "Equity Multiple tells you how much your initial investment has grown across all vectors (cash flow, principal paydown, and appreciation). Unlike IRR, it does not account for the time value of money, but it clearly answers: 'If I put in $1, how much total wealth do I have now?'",
          benchmarks: [
            { label: 'Break-even', value: '1.00x' },
            { label: 'Solid Core Investment (5-7 yrs)', value: '1.50x – 2.00x' },
            { label: 'Home Run / Heavy Value-Add', value: '2.50x+' },
          ]
        }
      case 'cash-deployed':
        return {
          title: 'Total Cash Deployed',
          value: formatCurrency(calc.totalDeployed),
          color: 'var(--yellow)',
          formula: 'Down Payment + Total Closing Costs = Total Cash Deployed',
          math: `${formatCurrency(calc.downPayment)} + ${formatCurrency(prop.closing_costs)} = ${formatCurrency(calc.totalDeployed)}`,
          meaning: "This is your true 'skin in the game'. It's the total upfront, un-leveraged capital you wired to the title company on closing day. This number forms the denominator for nearly all return-on-investment calculations.",
          benchmarks: [
            { label: 'FHA / Primary Hustle', value: '3.5% – 5% down' },
            { label: 'Standard Investment Loan', value: '20% – 25% down' },
            { label: 'DSCR / Commercial Loan', value: '20% – 30% down' },
          ]
        }
      case 'interest-ratio':
        return {
          title: 'Interest to Principal Ratio',
          value: calc.interestRatio != null ? `${calc.interestRatio.toFixed(2)} : 1` : '—',
          color: 'var(--orange)',
          formula: 'Total Interest Paid to Date ÷ Total Principal Paid to Date',
          math: `${formatCurrency(calc.totalInterestPaid)} ÷ ${formatCurrency(calc.totalPrincipalPaid)} = ${calc.interestRatio ? calc.interestRatio.toFixed(2) : '—'}`,
          meaning: "A 30-year fixed mortgage is heavily front-loaded with interest. In the early years, you might pay $4 in interest for every $1 of principal you pay down. Over time, as the principal decreases, this ratio flips in your favor.",
          benchmarks: [
            { label: 'Years 1-5 (7% Rate)', value: 'approx 4.0 – 6.0 : 1' },
            { label: 'Years 15-20 (Midway)', value: 'approx 1.5 – 1.0 : 1' },
            { label: 'Years 25-30 (Payoff)', value: 'Sub 0.5 : 1' },
          ]
        }
      case 'total-return':
        return {
          title: 'Total Annualized Return',
          value: calc.totalAnnualizedReturn != null ? formatPct(calc.totalAnnualizedReturn) : '—',
          color: 'var(--purple)',
          formula: '(Annual Cash Flow + Annual Principal Paydown + Annual Appreciation) ÷ Total Cash Deployed',
          math: `(${formatCurrency(calc.annualCF ?? 0)} + ${formatCurrency(calc.annualPrincipal ?? 0)} + ${formatCurrency(calc.annualAppreciation ?? 0)}) ÷ ${formatCurrency(calc.totalDeployed)} = ${calc.totalAnnualizedReturn ? (calc.totalAnnualizedReturn/100).toFixed(4) : '—'}`,
          mathBreakdown: [
            `Annualized Cash Flow (${formatCurrency(calc.annualCF ?? 0)}): Pure operational profit taking into account all expenses and debt service.`,
            `Annual Principal Paydown (${formatCurrency(calc.annualPrincipal ?? 0)}): The amount of the mortgage loan that the tenant paid down for you this year.`,
            `Annual Appreciation (${formatCurrency(calc.annualAppreciation ?? 0)}): The estimated growth in property value annualized over the hold period.`,
            `Total Cash Deployed (${formatCurrency(calc.totalDeployed)}): The denominator. Down payment + closing costs.`
          ],
          meaning: "Total Annualized Return acts like a simplified IRR (Internal Rate of Return). It takes all three major wealth generation distinct vectors of real estate—cash flow, mortgage paydown, and equity appreciation—and aggregates them into one powerful percentage. This lets you compare your entire real estate engine directly against the S&P 500 or bond yields.",
          benchmarks: [
            { label: 'S&P 500 Average', value: '7.0% – 10.0%' },
            { label: 'Healthy Real Estate Total Return', value: '12.0% – 18.0%' },
            { label: 'Exceptional Performers', value: '20.0%+' },
          ]
        }
      case 'roe':
        return {
          title: 'Return on Equity (ROE)',
          value: calc.roe != null ? formatPct(calc.roe) : '—',
          color: 'var(--yellow)',
          formula: 'Annualized Cash Flow ÷ Current Capitalized Net Equity',
          math: `${formatCurrency(calc.annualCF ?? 0)} ÷ ${formatCurrency(calc.capitalizedNetEq ?? 0)} = ${calc.roe ? (calc.roe/100).toFixed(4) : '—'}`,
          mathBreakdown: [
            `Annualized Cash Flow (${formatCurrency(calc.annualCF ?? 0)}): Your net operating P&L extended to a 12-month period based on historicals.`,
            `Capitalized Net Equity (${formatCurrency(calc.capitalizedNetEq ?? 0)}): The exact dollar amount of cash you would walk away with if you sold the property tomorrow (Value - Remaining Debt - Estimated 8% Selling Costs).`
          ],
          meaning: "ROE is an extremely advanced metric that helps you answer: 'Should I sell or refinance?' While your initial Cash-on-Cash return might have been 15%, as your equity grows over the years through appreciation and loan paydown, your ROE will drop. If your ROE drops below 4%, it means you have hundreds of thousands of dollars of equity trapped in the house generating very little cash, signaling it might be time for a cash-out refinance to buy another property.",
          benchmarks: [
            { label: 'Highly Efficient Equity (Recent Buy)', value: '10.0% – 15.0%' },
            { label: 'Maturing Investment', value: '5.0% – 8.0%' },
            { label: 'Trapped Dead Equity (Consider Refi/Sell)', value: 'Below 4.0%' },
          ]
        }
      case 'grm':
        return {
          title: 'Gross Yield (GRM Inverse)',
          value: calc.grm != null ? formatPct(calc.grm) : '—',
          color: 'var(--pink)',
          formula: 'Annual Gross Rent ÷ Current Property Value',
          math: `${formatCurrency(calc.annualRent ?? 0)} ÷ ${formatCurrency(prop.current_value ?? prop.purchase_price)} = ${calc.grm ? (calc.grm/100).toFixed(4) : '—'}`,
          meaning: "Gross Yield (which is the inverse of the Gross Rent Multiplier) is the simplest, most primitive real estate metric. It completely ignores expenses, taxes, and debt. It exists purely to give you a 5-second sanity check on whether a property's asking price makes sense relative to the market rents it can command.",
          benchmarks: [
            { label: 'The 1% Rule (Monthly Rent = 1% Value)', value: '12.0% Annual' },
            { label: 'Standard B/C Class Target', value: '8.0% – 10.0%' },
            { label: 'Expensive Coastal Markets', value: '4.0% – 6.0%' },
          ]
        }
      case 'breakeven-occupancy':
        return {
          title: 'Break-Even Occupancy Ratio',
          value: calc.breakEvenOccupancy != null ? formatPct(calc.breakEvenOccupancy) : '—',
          color: 'var(--teal)',
          formula: '(Annual Operating Expenses + Annual Debt Service) ÷ Gross Potential Rent',
          math: `(${formatCurrency(calc.annualOpExp ?? 0)} + ${formatCurrency(calc.annualDebtService ?? 0)}) ÷ ${formatCurrency(calc.annualRent ?? 0)} = ${calc.breakEvenOccupancy ? (calc.breakEvenOccupancy/100).toFixed(4) : '—'}`,
          mathBreakdown: [
            `Total Hard Costs (${formatCurrency((calc.annualOpExp ?? 0) + (calc.annualDebtService ?? 0))}): Your mortgage, taxes, insurance, HOA, and base-line operating expenses combined.`,
            `Gross Rent (${formatCurrency(calc.annualRent ?? 0)}): The maximum revenue you make if fully occupied 100% of the year.`
          ],
          meaning: "This tells you exactly how bulletproof your investment is against vacancies. If your Break-Even Occupancy is 70%, that means 30% of your units (or 3.6 months out of the year for a single family house) can sit utterly empty, and you STILL will not have to pull money out of your own pocket to pay the bank.",
          benchmarks: [
            { label: 'Bulletproof (Extremely Safe)', value: 'Below 65%' },
            { label: 'Standard Safe Target', value: '70% – 75%' },
            { label: 'Risky / Thin Margins', value: 'Above 85%' },
          ]
        }
      case 'oer':
        return {
          title: 'Operating Expense Ratio (OER)',
          value: calc.oer != null ? formatPct(calc.oer) : '—',
          color: 'var(--red)',
          formula: 'Annual Operating Expenses ÷ Gross Operating Income',
          math: `${formatCurrency(calc.annualOpExp ?? 0)} ÷ ${formatCurrency(calc.annualRent ?? 0)} = ${calc.oer ? (calc.oer/100).toFixed(4) : '—'}`,
          meaning: "OER measures how lean your property runs. It shows what percentage of your rental income is vaporized by taxes, insurance, maintenance, property management, and HOAs before you even reach the mortgage. Because it excludes mortgage payments, it's a pure indicator of management efficiency.",
          benchmarks: [
            { label: 'Extremely Lean (Self-Managed / No HOA)', value: '25% – 35%' },
            { label: 'Industry Standard "50% Rule"', value: '45% – 50%' },
            { label: 'Very Heavy (High Taxes / Luxury HOA)', value: '55%+' },
          ]
        }
      case 'principal-yield':
        return {
          title: 'Principal Paydown Yield',
          value: calc.principalPaydownYield != null ? formatPct(calc.principalPaydownYield) : '—',
          color: 'var(--green)',
          formula: 'Annual Principal Paid ÷ Total Cash Deployed',
          math: `${formatCurrency(calc.annualPrincipal ?? 0)} ÷ ${formatCurrency(calc.totalDeployed)} = ${calc.principalPaydownYield ? (calc.principalPaydownYield/100).toFixed(4) : '—'}`,
          meaning: "Every time the tenant pays their rent, a portion of it goes directly into your bank's mortgage portal, reducing the amount you owe. This is literally an invisible forced-savings account. Principal Paydown Yield extracts that exact dollar amount and treats it as a percentage return on your initial down payment, proving that real estate is making you richer even in months when cash flow is zero.",
          benchmarks: [
            { label: 'Years 1-5 of a 30yr mortgage', value: '1.5% – 2.5% yield on down payment' },
            { label: 'Years 15-20 of a 30yr mortgage', value: '3.5% – 5.0% yield on down payment' },
            { label: '15-year mortgage', value: 'Highly accelerated (6.0%+)' },
          ]
        }
      default:
        return null
    }
  }

  const details = getMetricDetails()
  if (!details) return <div className="empty-state" style={{ marginTop: 80 }}><p>Metric not found.</p></div>

  return (
    <main className="page-content" style={{ maxWidth: 800 }}>
      {/* Back button */}
      <button onClick={() => navigate(-1)} className="btn btn-ghost" style={{ paddingLeft: 0, marginBottom: 24, alignSelf: 'flex-start' }}>
        ← Back to Overview
      </button>

      <div className="card" style={{ padding: '40px', borderTop: `6px solid ${details.color}` }}>
        <h1 style={{ fontSize: '2.5rem', marginBottom: 8 }}>{details.title}</h1>
        <div style={{ fontFamily: 'var(--font-mono)', fontWeight: 800, fontSize: '3rem', color: details.color, marginBottom: 32 }}>
          {details.value}
        </div>

        <div style={{ marginBottom: 40 }}>
          <h3 className="section-title" style={{ fontSize: '1rem', color: 'var(--text-muted)', marginBottom: 12 }}>What it tells you</h3>
          <p style={{ fontSize: '1.05rem', lineHeight: 1.6 }}>{details.meaning}</p>
        </div>

        <div style={{ padding: '24px', background: 'var(--surface-1)', borderRadius: 'var(--radius-lg)', border: '1px solid var(--border)', marginBottom: 40 }}>
          <h3 className="section-title" style={{ fontSize: '1rem', color: 'var(--text-muted)', marginBottom: 16 }}>The Calculation</h3>
          <div style={{ fontSize: '0.9rem', color: 'var(--text-muted)', marginBottom: 8 }}>{details.formula}</div>
          <div style={{ fontFamily: 'var(--font-mono)', fontSize: '1.25rem', padding: '16px', background: 'var(--surface-3)', borderRadius: 'var(--radius-md)', fontWeight: 600, marginBottom: details.mathBreakdown ? 20 : 0 }}>
            {details.math}
          </div>
          {details.mathBreakdown && (
            <div style={{ display: 'flex', flexDirection: 'column', gap: 12, marginTop: 16 }}>
              {details.mathBreakdown.map((txt, idx) => {
                const [boldPart, rest] = txt.split(/:(.+)/)
                return (
                  <div key={idx} style={{ fontSize: '0.875rem', color: 'var(--text-subtle)', display: 'flex', gap: 8, alignItems: 'flex-start' }}>
                    <span style={{ color: details.color, fontSize: '1.2rem', lineHeight: '1rem' }}>•</span>
                    <div>
                      {rest ? <><strong style={{ color: 'var(--text-muted)' }}>{boldPart}:</strong>{rest}</> : txt}
                    </div>
                  </div>
                )
              })}
            </div>
          )}
        </div>

        <div>
          <h3 className="section-title" style={{ fontSize: '1rem', color: 'var(--text-muted)', marginBottom: 16 }}>Industry Benchmarks</h3>
          <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
            {details.benchmarks.map((b, i) => (
              <div key={i} style={{ display: 'flex', justifyContent: 'space-between', padding: '16px 20px', background: 'var(--surface-3)', borderRadius: 'var(--radius-md)' }}>
                <span style={{ fontWeight: 500 }}>{b.label}</span>
                <span style={{ fontFamily: 'var(--font-mono)', color: 'var(--text-muted)' }}>{b.value}</span>
              </div>
            ))}
          </div>
        </div>
      </div>
    </main>
  )
}
